[ tf-aws ]
# vpc can be set to "new" or "existing"
vpc = "existing"
# vpc_lambda will ensure that lambda functions are created within the vpc on the private subnet
vpc_lambda = true
# vpc_api_gateway will ensure that the api gateway is created within the vpc on the private subnet
vpc_api_gateway = true
# The following parameters will be required if using "existing" vpc
vpc_id = "vpc-01fd3deac4894cb39"
private_subnet_id = "subnet-0720d314ea172fb19"
public_subnet_id = "subnet-0e8ea3ad2a094a154"